blank_issues_enabled: false
contact_links:
  - name: ReActor Extension Community Support
    url: https://github.com/Gourieff/sd-webui-reactor-force/discussions
    about: Please ask and answer questions here.
